name = "notes-api"
compatibility_date = "2023-12-01"
compatibility_flags = ['nodejs_compat']

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "notes"
database_id = "1d688442-462d-44bc-9bc5-aa60ed6eaac5"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "working-notes"
